# Generated by Django 4.1.3 on 2022-12-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='ads',
            new_name='items',
        ),
    ]
