# Generated by Django 4.1.3 on 2022-12-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_ads_selection_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['id'], 'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
        migrations.AlterField(
            model_name='selection',
            name='items',
            field=models.ManyToManyField(to='ads.ad', verbose_name='Объявления'),
        ),
    ]
