# Generated by Django 4.1.3 on 2022-12-11 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_slug_alter_ad_description_alter_ad_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
