# Generated by Django 4.1.3 on 2022-12-11 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^[A-Za-z0-9._%+-]+@rambler\\.ru$')]),
        ),
    ]
