# Generated by Django 4.1.3 on 2022-12-11 18:06

import authentication.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=authentication.models.NonRamblerEmailField(max_length=254, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^[A-Za-z0-9._%+-]+@rambler\\.ru$')]),
        ),
    ]
